services:
  nestjs_test:
    build: 
      context: .
      dockerfile: Dockerfile.test
      target: test
    env_file:
      - src/config/env/.env.test
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src

