name: Deploy CMS ECS on AWS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build CMS Package Image"]
    types:
      - completed
  push:
    branches:
      - master
      - stg
      - prod

jobs:
  check_workflow:
    runs-on: ubuntu-latest
    name: Check Workflow & Changes
    outputs:
      should_run: ${{ steps.set_output.outputs.should_run }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check if Workflow is Running
        id: check_running
        run: |
          RUNNING_COUNT=$(gh api repos/${{ github.repository }}/actions/runs \
            --jq '[.workflow_runs[] | select(.name=="Build CMS Package Image" and .status=="in_progress")] | length')

          if [[ "$RUNNING_COUNT" -gt 0 ]]; then
            echo "Build CMS Package Image workflow is running, skipping deployment."
            echo "should_run=false" >> $GITHUB_ENV
          else
            echo "No running workflows, checking for file changes..."
            echo "should_run=true" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Output
        id: set_output
        run: echo "should_run=${{ env.should_run }}" >> $GITHUB_OUTPUT

  run_cicd2:
    needs: check_workflow
    runs-on: ubuntu-latest
    name: Deploy CMS to AWS ECS
    environment: ${{ github.ref_name }}
    if: > 
      github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' ||
      github.event_name == 'push' && needs.check_workflow.outputs.should_run == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build, tag, and push image to AWS ECR backend
        id: build-image-cms
        run: |
          docker build -t test2 -f Dockerfile .

      - name: Deploy to AWS ECS
        id: deploy
        run: |
          echo "Deploying to AWS ECS..."
