name: Build CMS Package Image

on:
  workflow_dispatch:


jobs:
  build_image:
    runs-on: ubuntu-latest
    name: BUILD CMS PACKAGE IMAGE
    environment:  ${{ github.ref_name }}      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      
      - name: Build, tag, and push image to AWS ECR backend
        id: build-image-cms
        run: |
          if [ "${{ secrets.STAGE }}" == "uat" ]; then
            echo "uat"
          fi
          docker build -t test -f Dockerfile .
