name: Deploy CMS ECS on AWS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build CMS Package Image"]
    types:
      - completed
  push:
    branches:
      - master
      - stg
      - prod

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: DEPLOY CMS
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for Changes in Package Repo
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)

          if echo "$CHANGED_FILES" | grep -q '^src/'; then
            echo "Changes detected in the packages repo"
            echo "has_changes=true" >> $GITHUB_ENV
          else
            echo "No changes in the packages repo"
            echo "has_changes=false" >> $GITHUB_ENV
          fi

    if: > 
      github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' || 
      (github.event_name == 'push' && env.has_changes == 'true')

    steps:
      - name: Build, tag, and push image to AWS ECR backend
        id: build-image-cms
        run: |
          docker build -t test2 -f Dockerfile .
